# Generated by Django 3.2 on 2021-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210603_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
