# Generated by Django 3.2 on 2021-06-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0003_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(to='api.Book')),
                ('products', models.ManyToManyField(to='api.Product')),
            ],
            options={
                'ordering': ['cart_id', '-created_at'],
            },
        ),
    ]
